export { default as Welcome } from './Authentication/Welcome'
export { default as SignIn } from './Authentication/SignIn'
export { default as SignUp } from './Authentication/SignUp'
export { default as Home } from './Home'
export { default as Rides } from './Rides'
export { default as Profile } from './Profile'
export { default as Services} from './Services'
export { default as About } from './About'
export { default as Help } from './Help'
export { default as Childrens } from './Childrens'
export { default as ManagePrivacy } from './ManagePrivacy'
export { default as PersonalInformation } from './PersonalInformation'
export { default as AccountInformation } from './AccountInformation'
export { default as RequestRide } from './RequestRide'
export { default as EmailVerfication } from './EmailVerfication'


